# Generated by Django 3.0.7 on 2020-06-25 02:17

import careers.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('dob', models.DateField(help_text='Provide the date in format yyyy-mm-dd', verbose_name='Date of Birth')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Id')),
                ('resume', models.FileField(null=True, upload_to='resume', validators=[careers.validators.validate_file_extension], verbose_name='Upload Resume')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Job Title')),
                ('descr', models.TextField(max_length=500, verbose_name='Job Description')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('applicants', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='careers.Applicant', verbose_name='Applicants')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
