# Generated by Django 3.0.7 on 2020-06-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='applicants',
        ),
    ]
