# Generated by Django 3.0.7 on 2020-06-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_remove_job_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='descr',
            field=models.TextField(max_length=5000, verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Job Title'),
        ),
    ]
