# Generated by Django 3.0.7 on 2020-07-07 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=500, verbose_name='Keyword')),
                ('relevance', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Relevance')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.Job', verbose_name='Job')),
            ],
        ),
    ]
