# Generated by Django 3.0.7 on 2020-07-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_jobanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobanalysis',
            name='relevance',
            field=models.DecimalField(decimal_places=6, max_digits=19, verbose_name='Relevance'),
        ),
    ]
