# Generated by Django 3.0.7 on 2020-07-17 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0006_auto_20200706_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=500, verbose_name='Keyword')),
                ('relevance', models.DecimalField(decimal_places=6, max_digits=19, verbose_name='Relevance')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.Applicant', verbose_name='Applicant')),
            ],
        ),
    ]
