# Generated by Django 3.0.7 on 2020-07-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0008_application_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='matched_keywords',
            field=models.TextField(default='', verbose_name='Matched Keywords'),
        ),
    ]
